In [1]:
# @hidden_cell

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [6]:
np.random.dirichlet?

In [10]:
import collections
d = np.random.randint(5, size=10)
cnt = collections.Counter(d)


In [21]:
x = np.ones(5)

In [25]:
d

array([1, 0, 1, 4, 2, 3, 3, 4, 3, 3])

In [23]:
x[d] += 1

In [26]:
x[d]

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [19]:
np.array(cnt.values()) + np.ones(5)

TypeError: unsupported operand type(s) for +: 'dict_values' and 'float'

In [36]:
np.array(list(cnt.values())) + np.ones(5)

array([ 3.,  2.,  3.,  2.,  5.])

In [29]:
np.random.dirichlet(list(cnt.values()))

array([ 0.0818749 ,  0.09686935,  0.23071208,  0.00265612,  0.58788756])

In [31]:
collections.Counter?

In [32]:
cnt

Counter({0: 1, 1: 2, 2: 1, 3: 4, 4: 2})

In [37]:
cnt

Counter({0: 1, 1: 2, 2: 1, 3: 4, 4: 2})

In [38]:
cnt + collections.Counter(np.arange(5))

Counter({0: 2, 1: 3, 2: 2, 3: 5, 4: 3})

In [ ]:
a=np.array([1,8,9])

In [ ]:
a.pop()